[4/20/2025 10:30:24 PM] System Error: System.InvalidOperationException: The connection is already open
   at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__94.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at DAL.AccountAccess.UpdatePassword(String email, String password) in C:\Users\ASUS\OneDrive\Máy tính\New folder\RentEase\DAL\AccountAccess.cs:line 128
[4/20/2025 10:57:03 PM] System Error: System.InvalidOperationException: The connection is already open
   at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__94.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at DAL.AccountAccess.UpdatePassword(String email, String password) in C:\Users\ASUS\OneDrive\Máy tính\New folder\RentEase\DAL\AccountAccess.cs:line 128
[4/20/2025 11:01:09 PM] System Error: System.InvalidOperationException: The connection is already open
   at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__94.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at DAL.AccountAccess.UpdatePassword(String email, String password) in C:\Users\ASUS\OneDrive\Máy tính\New folder\RentEase\DAL\AccountAccess.cs:line 128
[4/20/2025 11:03:52 PM] System Error: System.InvalidOperationException: The connection is already open
   at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__94.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at DAL.AccountAccess.UpdatePassword(String email, String password) in C:\Users\ASUS\OneDrive\Máy tính\New folder\RentEase\DAL\AccountAccess.cs:line 128
[4/20/2025 11:22:59 PM] System Error: System.InvalidOperationException: The connection is already open
   at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__94.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at DAL.AccountAccess.UpdatePassword(String email, String password) in C:\Users\ASUS\OneDrive\Máy tính\New folder\RentEase\DAL\AccountAccess.cs:line 128
